name: Daily CANSLIM Scan

on:
schedule:
- cron: '0 4 * * *' # Todos los días a las 4 AM
workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.9'

  - name: Install dependencies
    run: |
      pip install yfinance pandas numpy lxml

  - name: Run scanner
    run: python escaner_real.py

  - name: Commit results
    run: |
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      git add data.json
      git commit -m "Update data" || exit 0
      git push
